### ISSUE TITLE
Accessing outputs from a step

### ISSUE THREAD

**Issue by preethidh** [jbutcher5/read-yaml#42]
Where are the output's getting stored.

**Comment by preethidh** [comment]
Warning: Unexpected input(s) 'file', 'key-path', valid inputs are ['repository', 'ref', 'token', 'clean', 'submodules', 'lfs', 'fetch-depth', 'path'] - I am getting this warning and unable to see the Output (not printing).

**Comment by KJ002** [comment]
Hey @preethidh, I hope this clears things up. `outputs` is an attribute of the step id that is using read-yaml. You must specify an id attribute on the step in order to access the outputs which has the data about which would be the value at the key you have given. I am not very good at explaining things to people so please don't hesitate to ask another question if this helps but you would take a look at the example on the readme and see how the step that we are calling read-yaml on has an id attribute (I hope you know what I mean by "attribute") and then in the following step we are using that attribute to access `.outputs.data` (this will always be constant).

**Comment by preethidh** [comment]
Hi @KJ002, Thanks for your response.

I am new to Github actions & below is my yaml file,

name: "Read Yaml"

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test-yaml-reader:
    name: 'Test read-yaml'
    runs-on: ubuntu-latest

    steps:
      - name: Run read-yaml action
        uses: actions/checkout@v1
        with:
          file: './dev.yaml'
          key-path: '["chart", "name"]'

      - name: Get read-yaml output
        run: echo "${{ steps.yaml-data.outputs.data }}"

were as i need to get data from dev.yaml & i observe below error. Am I doing it right? or any modification required.

**Warning: Unexpected input(s) 'file', 'key-path', valid inputs are ['repository', 'ref', 'token', 'clean', 'submodules', 'lfs', 'fetch-depth', 'path']**

**Comment by KJ002** [comment]
One slight modification needs to be made.

```yaml
name: "Read Yaml"

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test-yaml-reader:
    name: 'Test read-yaml'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Run read-yaml action
        uses: KJ002/read-yaml@main
        id: chart-name
        with:
          file: './dev.yaml'
          key-path: '["chart", "name"]'

      - name: Get read-yaml output
        run: echo "${{ steps.chart-name.outputs.data }}"
```

I haven't tried it but this hopefully should work.

**Comment by preethidh** [comment]
works good now!! Thank you :)

**Comment by preethidh** [comment]
Now i am trying to get 2 values from same yaml file, but nothing is printing now.

name: "Read Yaml"

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test-yaml-reader:
    name: 'Test read-yaml'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1
        
      - name: List       
        run : ls -laR ./.github/workflows/

      - name: Run read-yaml action - name
        uses: repo@master
        id: chart-name
        with:
          file: './dev.yaml'
          key-path: '["chart", "name"]'

      - name: Run read-yaml action - version
        uses: repo@master
        id: chart-version
        with:
          file: './dev.yaml'         
          key-path: '["chart", "version"]'

      - name: Get read-yaml output
        run: echo "${{ steps.chart-name.outputs.data }}"

**Comment by KJ002** [comment]
You're using `repo@master` not `KJ002/read-yaml@main`

**Comment by preethidh** [comment]
yeah, i am trying to replicate same in my Github repo.

**Comment by KJ002** [comment]
Unless your repo is located at `https://github.com/repo` then this isn't going to work, you need to be using my repo for me to be able to provide help.

**Comment by preethidh** [comment]
its located in https://github.com/repo - for example lets take KJ002/read-yaml@main as an example and the yaml should read multiple data and print it.

**Comment by KJ002** [comment]
I was alluding to that it isn't possible for this to be a valid action `repo@master`

**Comment by preethidh** [comment]
Let me give the .yaml file here,

name: "Read Yaml"

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test-yaml-reader:
    name: 'Test read-yaml'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Run read-yaml action - App name
        uses: PD/POC@master
        id: chart-name
        with:
          file: './dev.yaml'
          key-path: '["chart", "name"]'

      - name: Run read-yaml action - Version
        uses: PD/POC@master
        id: chart-version
        with:
          file: './dev.yaml'         
          key-path: '["chart", "targetRevision"]'

      - name: Get read-yaml output
        run: echo "${{ steps.chart-name.outputs.data }}"
        
        Be it any repo in place of KJ002/read-yaml@main

**Comment by preethidh** [comment]
i am trying to get two values using this github action but prints only the "name" but not "version". Am I doing it right or anything needs to be modified.

**Comment by KJ002** [comment]
There is no public repo with called `POC` under the user `PD`, it needs to be public.

**Comment by preethidh** [comment]
okay lets take your repo as an example,

will i be able to read and print 2 values from a .yaml file.

**Comment by KJ002** [comment]
yes

**Comment by preethidh** [comment]
that's what actually i am trying and unable to print the 2 one (value).

**Comment by KJ002** [comment]
Try time

```yaml
name: "Read Yaml"

on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main

jobs:
  test-yaml-reader:
    name: 'Test read-yaml'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Run read-yaml action - App name
        uses: KJ002/read-yaml@main
        id: chart-name
        with:
          file: './dev.yaml'
          key-path: '["chart", "name"]'

      - name: Run read-yaml action - Version
        uses: KJ002/read-yaml@main
        id: chart-version
        with:
          file: './dev.yaml'         
          key-path: '["chart", "targetRevision"]'

      - name: Get read-yaml output
        run: echo "${{ steps.chart-name.outputs.data }}"
```

**Comment by preethidh** [comment]
Still below is not working as expected,

      - name: Run read-yaml action - Version
        uses: KJ002/read-yaml@main
        id: chart-version
        with:
          file: './dev.yaml'         
          key-path: '["chart", "targetRevision"]'

**Comment by KJ002** [comment]
I have just tried accessing two variables in this repo's test github action and it seems to work completely fine

**Comment by KJ002** [comment]
This is what I have for this repositories github action and it seems to work fine
```yaml

on: [ push, pull_request ]

jobs:
  test-yaml-reader:
    runs-on: ubuntu-latest
    name: Test read-yaml
    steps:
      - uses: actions/checkout@v1

      - name: Run read-yaml action
        id: using
        uses: ./
        with:
          file: './action.yml'
          key-path: '["runs", "using"]'
      
      - name: Run read-yaml action
        id: desc
        uses: ./
        with:
          file: './action.yml'
          key-path: '["output", "data", "description"]'
          
      - name: Get read-yaml using output
        run: echo "${{ steps.using.outputs.data }}"
        
      - name: Get read-yaml description output
        run: echo "${{ steps.desc.outputs.data }}"
        ```
